package edu.pojo;
// Generated 16 Apr, 2013 10:53:37 PM by Hibernate Tools 3.1.0.beta4



/**
 * Coursestudentmap generated by hbm2java
 */

public class Coursestudentmap  implements java.io.Serializable {


    // Fields    

     private int csid;
     private Course course;
     private Student student;


    // Constructors

    /** default constructor */
    public Coursestudentmap() {
    }

    
    /** full constructor */
    public Coursestudentmap(int csid, Course course, Student student) {
        this.csid = csid;
        this.course = course;
        this.student = student;
    }
    

   
    // Property accessors

    public int getCsid() {
        return this.csid;
    }
    
    public void setCsid(int csid) {
        this.csid = csid;
    }

    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }

    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
   








}
