package edu.pojo;
// Generated 16 Apr, 2013 10:53:37 PM by Hibernate Tools 3.1.0.beta4

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Course generated by hbm2java
 */

public class Course  implements java.io.Serializable {


    // Fields    

     private String courseId;
     private String courseName;
     private String courseSection;
     private Date meetingTime;
     private String location;
     private Set coursestudentmaps = new HashSet(0);
     private Set courseinstructormaps = new HashSet(0);


    // Constructors

    /** default constructor */
    public Course() {
    }

	/** minimal constructor */
    public Course(String courseId, String courseName, String courseSection, String location) {
        this.courseId = courseId;
        this.courseName = courseName;
        this.courseSection = courseSection;
        this.location = location;
    }
    
    /** full constructor */
    public Course(String courseId, String courseName, String courseSection, Date meetingTime, String location, Set coursestudentmaps, Set courseinstructormaps) {
        this.courseId = courseId;
        this.courseName = courseName;
        this.courseSection = courseSection;
        this.meetingTime = meetingTime;
        this.location = location;
        this.coursestudentmaps = coursestudentmaps;
        this.courseinstructormaps = courseinstructormaps;
    }
    

   
    // Property accessors

    public String getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }

    public String getCourseName() {
        return this.courseName;
    }
    
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    public String getCourseSection() {
        return this.courseSection;
    }
    
    public void setCourseSection(String courseSection) {
        this.courseSection = courseSection;
    }

    public Date getMeetingTime() {
        return this.meetingTime;
    }
    
    public void setMeetingTime(Date meetingTime) {
        this.meetingTime = meetingTime;
    }

    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    public Set getCoursestudentmaps() {
        return this.coursestudentmaps;
    }
    
    public void setCoursestudentmaps(Set coursestudentmaps) {
        this.coursestudentmaps = coursestudentmaps;
    }

    public Set getCourseinstructormaps() {
        return this.courseinstructormaps;
    }
    
    public void setCourseinstructormaps(Set courseinstructormaps) {
        this.courseinstructormaps = courseinstructormaps;
    }
   








}
