package edu.pojo;
// Generated 16 Apr, 2013 10:53:37 PM by Hibernate Tools 3.1.0.beta4

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Instructor generated by hbm2java
 */

public class Instructor  implements java.io.Serializable {


    // Fields    

     private String instructorId;
     private Person person;
     private String department;
     private Date officeHours;
     private Set courseinstructormaps = new HashSet(0);


    // Constructors

    /** default constructor */
    public Instructor() {
    }

	/** minimal constructor */
    public Instructor(String instructorId, Person person) {
        this.instructorId = instructorId;
        this.person = person;
    }
    
    /** full constructor */
    public Instructor(String instructorId, Person person, String department, Date officeHours, Set courseinstructormaps) {
        this.instructorId = instructorId;
        this.person = person;
        this.department = department;
        this.officeHours = officeHours;
        this.courseinstructormaps = courseinstructormaps;
    }
    

   
    // Property accessors

    public String getInstructorId() {
        return this.instructorId;
    }
    
    public void setInstructorId(String instructorId) {
        this.instructorId = instructorId;
    }

    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }

    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }

    public Date getOfficeHours() {
        return this.officeHours;
    }
    
    public void setOfficeHours(Date officeHours) {
        this.officeHours = officeHours;
    }

    public Set getCourseinstructormaps() {
        return this.courseinstructormaps;
    }
    
    public void setCourseinstructormaps(Set courseinstructormaps) {
        this.courseinstructormaps = courseinstructormaps;
    }
   








}
