package edu.pojo;
// Generated 16 Apr, 2013 10:53:37 PM by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * Student generated by hbm2java
 */

public class Student  implements java.io.Serializable {


    // Fields    

     private String studentId;
     private Person person;
     private Set coursestudentmaps = new HashSet(0);


    // Constructors

    /** default constructor */
    public Student() {
    }

	/** minimal constructor */
    public Student(String studentId, Person person) {
        this.studentId = studentId;
        this.person = person;
    }
    
    /** full constructor */
    public Student(String studentId, Person person, Set coursestudentmaps) {
        this.studentId = studentId;
        this.person = person;
        this.coursestudentmaps = coursestudentmaps;
    }
    

   
    // Property accessors

    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }

    public Set getCoursestudentmaps() {
        return this.coursestudentmaps;
    }
    
    public void setCoursestudentmaps(Set coursestudentmaps) {
        this.coursestudentmaps = coursestudentmaps;
    }
   








}
